package utils;

import lombok.Getter;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Getter
public class TreeNode {
    public int val;
    public TreeNode left;
    public TreeNode right;

    public TreeNode(int val) {
        this.val = val;
    }

    public TreeNode(int val, TreeNode left, TreeNode right) {
        this.val = val;
        this.left = left;
        this.right = right;
    }

    public static String treeToString(TreeNode root) {
        // Code generated by AI
        StringBuilder sb = new StringBuilder();
        buildString(root, sb, 0, "");
        return sb.toString();
    }

    private static void buildString(TreeNode node, StringBuilder sb, int depth, String prefix) {
        // Code generated by AI
        if (node == null) return;
        buildString(node.right, sb, depth + 1, prefix + "    ");
        sb.append(prefix).append(node.val).append("\n");
        buildString(node.left, sb, depth + 1, prefix + "    ");
    }
}
